#! /bin/bash

#this code only works when run from the tests directory

pyroot="/bin/python"
py2="2.7"
py3="3.5"

pyversion=()
test_array=()
test_status=()

#parse input arg
while [[ $# -ge 1 ]]
do
    case $1 in
    -2)
        pyversion+=( ${py2} )
    ;;
    -3)
        pyversion+=( ${py3} )
    ;;
    test*.py)
        test_array+=( $1 )
    ;;
    *)
        echo unknown argument $1
        exit 1
    ;;
    esac
    shift
done

#unless specified test both python 2 and 3
if [[ ${#pyversion[@]} -eq 0 ]]
then
    pyversion=( ${py2} ${py3} )
fi

#unless specified run all test*.py files
if [[ ${#test_array[@]} -eq 0 ]]
then
    for t in test*.py
    do
        test_array+=( ${t} )
    done
fi

#run each test for each python version
for test_name in ${test_array[@]}
do
    for vsn_no in ${pyversion[@]}
    do
        echo RUNNING ${test_name}
        ${pyroot}${vsn_no} ${test_name}
        test_status+=($?)
        echo FINISHED ${test_name}
    done
done

echo

#output pass/fail results
i=0
fail_count=0
total=${#test_status[@]}
for test_name in ${test_array[@]}
do
    for vsn_no in ${pyversion[@]}
    do
        stat_no=${test_status[$i]}
        if [ ${stat_no} == 0 ]
        then
            echo passed ${test_name} in python${vsn_no}
        else
            echo FAILED ${test_name} in python${vsn_no}
            fail_count=$(($fail_count + 1))
        fi
        i=$(($i + 1))
    done
done

#total score
echo
if [[ $fail_count -eq 0 ]]
then
    echo all tests passed
else
    echo failed ${fail_count} of ${total} tests.
fi

