iso2iea={\
 'afg':'oas',\
   'alb':'alb',\
   'dza':'dza',\
   'and':'fra',\
   'ago':'ago',\
   'ata':'',\
   'atg':'ola',\
   'arg':'arg',\
   'arm':'arm',\
   'aus':'aus',\
   'aut':'aut',\
   'aze':'aze',\
   'bhs':'ola',\
   'bhr':'bhr',\
   'bgd':'bgd',\
   'brb':'ola',\
   'bel':'bel',\
   'blz':'ola',\
   'ben':'ben',\
   'bmu':'ola',\
   'btn':'oas',\
   'bol':'bol',\
   'bih':'bih',\
   'bwa':'bwa',\
   'bra':'bra',\
   'brn':'brn',\
   'bgr':'bgr',\
   'bfa':'oaf',\
   'bdi':'oaf',\
   'blr':'blr',\
   'khm':'khm',\
   'cmr':'cmr',\
   'can':'can',\
   'cpv':'oaf',\
   'caf':'oaf',\
   'tcd':'oaf',\
   'chl':'chl',\
   'chn':'chn',\
   'col':'col',\
   'com':'oaf',\
   'cog':'cog',\
   'cri':'cri',\
   'hrv':'hrv',\
   'cub':'cub',\
   'cyp':'cyp',\
   'cze':'cze',\
   'dnk':'dnk',\
   'dji':'oaf',\
   'dma':'ola',\
   'dom':'dom',\
   'ecu':'ecu',\
   'egy':'egy',\
   'slv':'slv',\
   'gnq':'oaf',\
   'eri':'eri',\
   'est':'est',\
   'eth':'eth',\
   'flk':'gbr',\
   'fro':'dnk',\
   'fji':'oas',\
   'fin':'fin',\
   'fra':'fra',\
   'guf':'fra',\
   'pyf':'fra',\
   'gab':'gab',\
   'gmb':'oaf',\
   'gaz':'oas',\
   'geo':'geo',\
   'deu':'deu',\
   'gha':'gha',\
   'grc':'grc',\
   'grl':'dnk',\
   'grd':'ola',\
   'glp':'fra',\
   'gtm':'gtm',\
   'gin':'oaf',\
   'gnb':'oaf',\
   'guy':'ola',\
   'hti':'hti',\
   'hnd':'hnd',\
   'hkg':'hkg',\
   'hun':'hun',\
   'isl':'isl',\
   'ind':'ind',\
   'idn':'idn',\
   'irn':'irn',\
   'irq':'irq',\
   'isn':'oas',\
   'irl':'irl',\
   'xim':'gbr',\
   'isr':'isr',\
   'ita':'ita',\
   'civ':'civ',\
   'jam':'jam',\
   'sjm':'nor',\
   'jpn':'jpn',\
   'jor':'jor',\
   'kaz':'kaz',\
   'ken':'ken',\
   'ker':'fra',\
   'kir':'oas',\
   'prk':'prk',\
   'kor':'kor',\
   'kwt':'kwt',\
   'kgz':'kgz',\
   'lao':'oas',\
   'lva':'lva',\
   'lbn':'lbn',\
   'lso':'oaf',\
   'lbr':'oaf',\
   'lby':'lby',\
   'lie':'che',\
   'ltu':'ltu',\
   'lux':'lux',\
   'mac':'chn',\
   'mkd':'mkd',\
   'mdg':'oaf',\
   'mwi':'oaf',\
   'mys':'mys',\
   'mdv':'oas',\
   'mli':'oaf',\
   'mlt':'mlt',\
   'mtq':'fra',\
   'mrt':'oaf',\
   'mus':'oaf',\
   'mex':'mex',\
   'mda':'mda',\
   'mco':'fra',\
   'mng':'mng',\
   'mar':'mar',\
   'moz':'moz',\
   'mmr':'mmr',\
   'nam':'nam',\
   'npl':'npl',\
   'nld':'nld',\
   'ncl':'fra',\
   'nzl':'nzl',\
   'nic':'nic',\
   'ner':'oas',\
   'nga':'nga',\
   'mnp':'usa',\
   'nor':'nor',\
   'omn':'omn',\
   'pak':'pak',\
   'pan':'pan',\
   'png':'oas',\
   'pry':'pry',\
   'per':'per',\
   'phl':'phl',\
   'pol':'pol',\
   'prt':'prt',\
   'pri':'usa',\
   'qat':'qat',\
   'reu':'fra',\
   'rom':'rou',\
   'rus':'rus',\
   'rwa':'oaf',\
   'smr':'ita',\
   'stp':'oaf',\
   'sau':'sau',\
   'sen':'sen',\
   'syc':'oaf',\
   'sle':'oaf',\
   'sgp':'sgp',\
   'svk':'svk',\
   'svn':'svn',\
   'slb':'oas',\
   'som':'oaf',\
   'zaf':'zaf',\
   'esp':'esp',\
   'lka':'lka',\
   'scn':'gbr',\
   'lca':'ola',\
   'vct':'ola',\
   'sdn':'sdn',\
   'sur':'ola',\
   'sjm':'nor',\
   'swz':'oaf',\
   'swe':'swe',\
   'che':'che',\
   'syr':'syr',\
   'twn':'twn',\
   'tjk':'tjk',\
   'tza':'tza',\
   'tha':'tha',\
   'tgo':'tgo',\
   'ton':'oas',\
   'tto':'tto',\
   'tun':'tun',\
   'tur':'tur',\
   'tkm':'tkm',\
   'tca':'gbr',\
   'uga':'oaf',\
   'ukr':'ukr',\
   'are':'are',\
   'gbr':'gbr',\
   'usa':'usa',\
   'ury':'ury',\
   'uzb':'uzb',\
   'vut':'oas',\
   'ven':'ven',\
   'vnm':'vnm',\
   'esh':'oaf',\
   'wsm':'oas',\
   'yem':'yem',\
   'srb':'srb',\
   'yug':'srb',\
   'zar':'cod',\
   'zmb':'zmb',\
   'zwe':'zwe',\
   'ala':'fin',\
   'asm':'usa',\
   'aia':'gbr',\
   'abw':'ant',\
   'bes':'ant',\
   'bvt':'nor',\
   'iot':'gbr',\
   'cym':'gbr',\
   'cxr':'aus',\
   'cck':'aus',\
   'cok':'nzl',\
   'cuw':'ant',\
   'atf':'fra',\
   'gib':'gib',\
   'gum':'usa',\
   'ggy':'gbr',\
   'hmd':'aus',\
   'vat':'ita',\
   'hkg':'hkg',\
   'imn':'gbr',\
   'jey':'gbr',\
   'mhl':'usa',\
   'myt':'fra',\
   'fsm':'usa',\
   'mne':'srb',\
   'msr':'gbr',\
   'nru':'oas',\
   'niu':'nzl',\
   'nfk':'aus',\
   'plw':'usa',\
   'pse':'oas',\
   'pcn':'gbr',\
   'blm':'fra',\
   'shn':'gbr',\
   'kna':'ola',\
   'maf':'fra',\
   'spm':'fra',\
   'sxm':'ant',\
   'sgs':'gbr',\
   'ssd':'sdn',\
   'tls':'oas',\
   'tkl':'nzl',\
   'tuv':'oas',\
   'umi':'usa',\
   'vgb':'gbr',\
   'vir':'usa',\
   'wlf':'fra',\
   'nono':''}  #SALVI added this to neglect vulcan NoNo iso3 codes for US powerPlant
